############################################################
##                                                        ##
##          Log Configuration                             ##
##                                                        ##
############################################################
log:
  level: info